all:
  hosts:
    CORE-SW:
      ansible_host: 192.168.1.1
      ansible_user: rawen
      ansible_password: rawen123
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_become: true
      ansible_become_method: enable
      ansible_become_password: cisoc
